### ISSUE TITLE
About the visualizations of the paper

### ISSUE THREAD

**Issue by MAX-OTW** [deepguider/deattention_with_stml_for_vpr#1]
Hello, @sunglok @aseuteurideu @roricljy @ccsmm78 ,-I really appreciate for your work！Congratulations :)
The visualizations(like **Fig. 10.** Visualization of De-attention Result, and **Fig. 13.** Retrieval results and visualization for various cases) in the paper look great. Currently I want to try to implement them but I failed. Is it convenient to provide the relevant implementation code?Of course, detailed guidance would be better.
I am always looking forward to your kind response.
Best regards.

**Comment by ccsmm78** [comment]
Hello MAX-OTW^^. I'm Seung-Min Choi. You can visualize local features using Eq.9 as "Very deep convolutional networks for large-scale image recognition"

I've attached my code at https://github.com/ccsmm78/deattention_with_stml_for_vpr/blob/main/torch_img_utils.py
The code above was written for my experiments, so it may not work in your environment. Since the heatmap() function in line 431 implements Eq 9 in my PR paper, please refer to it.

**Comment by ccsmm78** [comment]
Hello MAX-OTW^^. I'm Seung-Min Choi. You can visualize local features using Eq.9 as "Very deep convolutional networks for large-scale image recognition"

I've attached my code at https://github.com/ccsmm78/deattention_with_stml_for_vpr/blob/main/torch_img_utils.py
The code above was written for my experiments, so it may not work in your environment. Since the heatmap() function in line 431 implements Eq 9 in my PR paper, please refer to it.
